[global]
  workgroup = WORKGROUP
  server role = standalone server
  map to guest = Bad User
  guest account = nobody
  smb ports = 445
  server min protocol = SMB2
  disable netbios = yes
  load printers = no
  printing = bsd
  printcap name = /dev/null

[controlled]
  path = /srv/controlled-share
  browseable = yes
  read only = yes
  guest ok = yes
