name: juice-shop
services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    cap_drop:
      - all
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
          pids: 100
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q --spider http://127.0.0.1:3000 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - juice-shop-lab
    restart: on-failure
    security_opt:
      - no-new-privileges
    volumes:
      - juice-shop-data:/juice-shop/data
      - juice-shop-ftp:/juice-shop/ftp
networks:
  juice-shop-lab:
    external: true
    name: juice-shop-lab
volumes:
  juice-shop-data:
  juice-shop-ftp: